rootProject.name = "backend"

include("common-lib")
include("common-security")
include("common-persistence")
include("common-storage")
include("common-customfields")
include("custom-field-service")
include("common-notifications")
include("common-monitoring")
include("notification-service")
include("discovery-server")
include("api-gateway")
include("auth-service")
include("user-service")
include("role-service")
include("department-service")
include("complaint-service")
include("storage-service")
include("face-service")
include("monitor-service")
