management:
  endpoints:
    web:
      exposure:
        include: health
  health:
    redis:
      enabled: false

server:
  port: ${DISCOVERY_SERVER_PORT:8761}

spring:
  application:
    name: discovery-server
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    hostname: localhost
  server:
    remote-region-registry-fetch-interval: ${DISCOVERY_SERVER_REFRESH_INTERVAL:5}