management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
  health:
    redis:
      enabled: false

server:
  port: ${DISCOVERY_SERVER_PORT:8761}
  error:
    include-stacktrace: never
    include-message: never

spring:
  application:
    name: discovery-server
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

discovery:
  security:
    username: ${DISCOVERY_USERNAME:}
    password: ${DISCOVERY_PASSWORD:}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  dashboard:
    enabled: ${DISCOVERY_DASHBOARD_ENABLED:true}
  instance:
    hostname: localhost
  server:
    remote-region-registry-fetch-interval: ${DISCOVERY_SERVER_REFRESH_INTERVAL:5}
